{% set name = "nebari" %}
{% set version = "2023.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nebari-{{ version }}.tar.gz
  sha256: 0676656970c321757e44397eec052e950a590c1d7cbdc14fec653fed2707c077

build:
  number: 0
  noarch: python
  entry_points:
    - nebari = nebari.cli.main:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - setuptools-scm
    - hatchling
  run:
    - __unix
    - python >=3.8,<4.0
    - hatchling
    - importlib_metadata

test:
  imports:
    - nebari
    - nebari.cli
  commands:
    - pip check
    - nebari --help
    - if [[ $(nebari --version) != {{ version }} ]]; then exit 1; else exit 0; fi
  requires:
    - pip

about:
  home: https://github.com/nebari-dev/nebari
  summary: A Jupyter and Dask-powered open source data science platform.
  dev_url: https://github.com/nebari-dev/nebari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - viniciusdc
    - iameskild
