{% set name = "nebari" %}
{% set version = "2024.12.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nebari-{{ version }}.tar.gz
  sha256: 66c58df6f4f0ee201869d4747bb5acaa3bd5f9c322d5e43a34c69f0f70d5e676

build:
  number: 1
  noarch: python
  entry_points:
    - nebari = nebari.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools-scm
    - hatchling
    - hatch-vcs
  run:
    - __unix
    - python >={{ python_min }},<4.0
    - auth0-python ==4.7.1
    - azure-identity ==1.12.0
    - azure-mgmt-containerservice ==26.0.0
    - azure-mgmt-resource ==23.0.1
    - bcrypt ==4.0.1
    - boto3 ==1.34.63
    - cloudflare ==2.11.7
    - google-auth ==2.31.0
    - google-cloud-compute ==1.19.1
    - google-cloud-container ==2.49.0
    - google-cloud-iam ==2.15.1
    - google-cloud-storage ==2.18.0
    - grpc-google-iam-v1 ==0.13.1
    - jinja2
    - python-kubernetes ==27.2.0
    - pluggy ==1.3.0
    - prompt-toolkit <=3.0.36,>=2.0
    - pydantic ==2.9.2
    - pynacl ==1.5.0
    - python-keycloak <4.0.0,>=3.9.0
    - questionary ==2.0.0
    - requests-toolbelt ==1.0.0
    - rich ==13.5.1
    - ruamel.yaml ==0.18.6
    - typer ==0.9.0
    - packaging ==23.2
    - typing-extensions ==4.11.0
test:
  imports:
    - nebari
  commands:
    - pip check
    - nebari --help
    - if [[ $(nebari --version) != {{ version }} ]]; then exit 1; else exit 0; fi
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nebari-dev/nebari
  summary: A Jupyter and Dask-powered open source data science platform.
  dev_url: https://github.com/nebari-dev/nebari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelovilla
    - dcmcand
    - viniciusdc
