{% set name = "nebari" %}
{% set version = "2023.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nebari-{{ version }}.tar.gz
  sha256: 0676656970c321757e44397eec052e950a590c1d7cbdc14fec653fed2707c077

build:
  number: 0
  noarch: python
  entry_points:
    - nebari = nebari.cli.main:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - setuptools-scm
    - hatchling
  run:
    - __unix
    - python >=3.8,<4.0
    - auth0-python==4.0.0
    - azure-identity==1.6.1
    - azure-mgmt-containerservice==16.2.0
    - bcrypt==4.0.1
    - boto3==1.26.54
    - cloudflare==2.11.1
    - kubernetes==25.3.0
    - pydantic==1.10.4
    - pynacl==1.5.0
    - python-keycloak==2.9.0
    - questionary==1.10.0
    - rich==13.2.0
    - ruamel.yaml==0.17.21
    - typer==0.7.0

test:
  imports:
    - nebari
    - nebari.cli
  commands:
    - pip check
    - nebari --help
    - if [[ $(nebari --version) != {{ version }} ]]; then exit 1; else exit 0; fi
  requires:
    - pip

about:
  home: https://github.com/nebari-dev/nebari
  summary: A Jupyter and Dask-powered open source data science platform.
  dev_url: https://github.com/nebari-dev/nebari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - viniciusdc
    - iameskild
